### ISSUE TITLE
Space of coarse_block_radius

### ISSUE THREAD

**Issue by normanrz** [arttumiettinen/pi2#9]
Quick question: In what coordinate system is the `coarse_block_radius` evaluated? If I set `coarse_block_radius = 400` and `coarse_binning = 4` is that 400 or 1600 voxels in the native voxel space?

**Comment by arttumiettinen** [comment]
Both `coarse_block_radius` and `fine_block_radius` are evaluated in the non-binned native voxel space. I have added a clarification of this in the default stitch settings template file.
